### ISSUE TITLE
ALL tweakers.net issues

### ISSUE THREAD

**Issue by TjeuKayim** [EasyDutch-uBO/EasyDutch#34]
## Important note by EasyDutch authors:
uBlock Origin uses four links to update our list in their add-on/extension.  <br>
The [`contentURL`](https://github.com/gorhill/uBlock/blob/00fb5f18b2d2d9f91bcefb7adfda8e16b8369132/assets/assets.json#L756) is instantly updated after a commit, our own [`EasyDutchCDN`](https://github.com/gorhill/uBlock/blob/00fb5f18b2d2d9f91bcefb7adfda8e16b8369132/assets/assets.json#L758C5-L758C64) is updated every two hours, the other two [`cdnURLs`](https://github.com/gorhill/uBlock/blob/00fb5f18b2d2d9f91bcefb7adfda8e16b8369132/assets/assets.json#L759-L760) are updated less.  <br>
If there is a fix you need immediately, I can update the [`jsDelivr cdnURL`](https://github.com/gorhill/uBlock/blob/00fb5f18b2d2d9f91bcefb7adfda8e16b8369132/assets/assets.json#L759) by going to https://www.jsdelivr.com/tools/purge, and our [`EasyDutchCDN`](https://github.com/gorhill/uBlock/blob/00fb5f18b2d2d9f91bcefb7adfda8e16b8369132/assets/assets.json#L758).

<hr>

### Prerequisites / Vereisten

- [X] I performed a [cursory search of the issue tracker](https://github.com/BPower0036/AdBlockFilters/issues) to avoid opening a duplicate issue / Geen **duplicaten**!!

### Describe the issue

Pages like https://tweakers.net/reviews/10768/gelikte-code-met-pyscaffold-python-projecten-ontwikkelen-als-een-pro.html are asking users to disable their adblocker.

### Notes

After debugging with dev tools, I found that adding `tweakers.net##+js(set, window.BannerManager, undefined)` to 'My filters' in uBlock Origin bypasses the anti adblock. Though I have no experience writing these rules.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/15987676/212563498-dc12bbef-ed8c-45ac-99f7-81337de503c4.png)

**Comment by TjeuKayim** [comment]
Sorry, I selected the wrong category, this should not have been labelled 'documentation'

**Comment by nicolaasjan** [comment]
Maybe better fix:

`tweakers.net##+js(aeld, bannerLoadEvent, adblock)` ?

**Comment by TheQuickFox** [comment]
De fix werkt niet meer zo te zien.

https://tweakers.net/reviews/10866/is-matter-de-toekomst-van-smarthome-alles-wat-je-moet-weten-over-deze-standaard.html

![Untitled](https://user-images.githubusercontent.com/30596092/219249451-86b9fd07-55ee-464b-a05b-ffaa26d4d5c4.jpg)

**Comment by JohnyP36** [comment]
Indeed. But there are two options now. 
 1. unblock `aa.tweakers.net`, which is not what we want as they track you via that domain
 2. block the notice

So, we will implement the second 'choice'.

**Comment by VanHamsteren** [comment]
The issue seems to be with this script: https://tweakers.net/x/build/components.016f7b17.js

The 016f7b17 part changes every once in a while, so you need a selector like this: 'components.*.js', but if you do that, the adblock-detection is gone, but so is the post moderation and post score.

Inside that script is the adblocker detection code, so you need to block scriptlets or replace some vars. Unfortunately, this is where my knowledge stops.

**Comment by nicolaasjan** [comment]
`||tweakers.net/x/build/components.*.js$script,first-party`
Article is readable, but  post moderation and post score are gone...

`tweakers.net##+js(aeld, , handleAdblockDetect)`
Seems ineffective.

Well, they succeeded...
Had to disable uBO on that article.

**Comment by mapx-** [comment]
```
@@||tweakers.net^$shide
@@||tweakers.nl^$xhr,domain=tweakers.net
```

**Comment by nicolaasjan** [comment]
> test first (for breakage)
> 
> `tweakers.net##+js(aeld, , /^e=>.*\(e\)$/)`

Seems to work (didn't encounter any breakage yet).
Of course you'll have to disable the latest commit (00da790):
`@@||tweakers.net/x/build/components.*.js$script,first-party`

**Comment by BPower0036** [comment]
@mapx- Fixed; choosen for the second solution because of https://github.com/uBlockOrigin/uAssets/issues/17294

**Comment by VanHamsteren** [comment]
I noticed that this rule was added:
`||tweakers.net/x/build/components.*.js$script,first-party`

If you comment out that rule, the site works again. This rule removes the adblock checker, but also removes the moderation options

**Comment by SnowballV** [comment]
Again, https://tweakers.net/ detection issue.
See:
https://tweakers.net/reviews/9892/all/zoekmachines-en-je-privacy-googelen-zonder-alles-prijs-te-geven.html

**Comment by BPower0036** [comment]
@SnowballV it should be fixed in https://github.com/EasyDutch-uBO/EasyDutch/commit/da679f804520d9987a3cc0a76cf4dd3eff2142b4

**Comment by SnowballV** [comment]
Purged and updated (twice), and refreshed the page, but on mentioned page, the issue is still there.

**Comment by BPower0036** [comment]
@SnowballV Most likely uBO used one of our CDN's to update. For those CDN's you have always to wait at least a day before the changes are applied.

**Comment by SnowballV** [comment]
Ah, OK, thanks very much.
I'll test again, tomorrow.

**Comment by BPower0036** [comment]
@SnowballV I have update two of the three CDN's, so if you try in 30 minutes again you have now 75% chance that it will work.

**Comment by SnowballV** [comment]
OK, thanks, I'll try in half an hour.

**Comment by BPower0036** [comment]
@JohnyP36 told me that my changes were not working tomorrow it should.

**Comment by SnowballV** [comment]
Thank you very much.
I purged and updated again, and now the issue is resolved.
https://tweakers.net/reviews/9892/all/zoekmachines-en-je-privacy-googelen-zonder-alles-prijs-te-geven.html
Thanks again.

**Comment by nicolaasjan** [comment]
I have fix ee715f0 received here, but still have the detection issue, even with uBO standard configuration.
`uBlock Origin 1.49.3b8`

![screenshot1](https://user-images.githubusercontent.com/14093220/236995117-344b2efc-3383-47d7-b8ed-8247280da2ce.png)

**Comment by Chrovax** [comment]
I had to refresh [the page](https://tweakers.net/reviews/9892/all/zoekmachines-en-je-privacy-googelen-zonder-alles-prijs-te-geven.html) a couple of times, the anti-adblock is gone now. Thanks for the fix.

**Comment by BPower0036** [comment]
Reopened this issue; every issue with Tweakers can now posted here in stead of opening new issues again and again.

**Comment by BPower0036** [comment]
Due to a new adblock message on **only** the homepage, I have broaden the last added rule.
I could find anything broken, if you find something, please report.
![afbeelding](https://github.com/EasyDutch-uBO/EasyDutch/assets/80090789/2f4878af-955c-4cb9-ad47-c098558fa8fe)

**Comment by Nomes77** [comment]
Sorry, for disturbing you. My issue labeler didn't do what it should have done.

**Comment by Nomes77** [comment]
Script for anti-adblock is now `https://tweakers.net/x/build/frontpage.50f1df5c.js`

**Comment by hp197** [comment]
Blocking of https://tweakers.net/x/styles/components/cookiebar/cookie_bar.fd6f85fcf49475b8103620f801820c56.css breaks the (cookie pref) model boxes:

<img width="1104" alt="Monosnap Gathering of Tweakers 2024-02-23 11-50-44" src="https://github.com/EasyDutch-uBO/EasyDutch/assets/9770340/30adf92c-7061-4545-9736-a708e11ac3fa">
<img width="1016" alt="Monosnap Tweakers - Jouw thuis voor tech 2024-02-23 11-50-21" src="https://github.com/EasyDutch-uBO/EasyDutch/assets/9770340/79f4cf63-ab9d-4820-9569-010f9dce0392">
<img width="1712" alt="Monosnap Tweakers - Jouw thuis voor tech 2024-02-23 11-49-42" src="https://github.com/EasyDutch-uBO/EasyDutch/assets/9770340/f27cb677-9e6f-4a6d-a9cd-9f6479184277">

easylist dutch, ublock lite.
